apiVersion: apps/v1
kind: Deployment
metadata:
  name: capacity-exporter
spec:
  selector:
    matchLabels:
      app: capacity-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: capacity-exporter
    spec:
      serviceAccountName: capacity-exporter
      containers:
      - name: capacity-exporter
        image: arhilazar/capacity-exporter
        imagePullPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hw
                operator: NotIn
                values:
                - cpu1ram2
                - cpu2ram4
              - key: zone
                operator: NotIn
                values:
                - 1a
                - 1c
              - key: dc
                operator: In
                values:
                - red
                - blue
